export {default as Blogs} from './blogs/Blogs'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Possibility} from './possibility/Possibility'
export {default as Whatiot} from './whatiot/Whatiot'
export {default as Features} from './features/Features'